#!/bin/sh
#
#
# OpenStack Orchestration Engine API Service (heat-api)
#
# Description:  Manages an OpenStack Orchestration Engine API Service (heat-api) process as an HA resource
#
# Authors:      Emilien Macchi
# Authors:      Nanuk Krinner <nkrinner@suse.de>
#
# Support:      openstack@lists.launchpad.net
# License:      Apache Software License (ASL) 2.0
#
#
# See usage() function below for more details ...
#
# OCF instance parameters:
#   OCF_RESKEY_binary
#   OCF_RESKEY_config
#   OCF_RESKEY_user
#   OCF_RESKEY_pid

#######################################################################
# Initialization:

: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

#######################################################################

# Fill in some defaults if no values are specified

OCF_RESKEY_binary_default="heat-api"
OCF_RESKEY_config_default="/etc/heat/heat.conf"
OCF_RESKEY_user_default="openstack-heat"
OCF_RESKEY_api_port_default="8004"

: ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
: ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
: ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
: ${OCF_RESKEY_api_port=${OCF_RESKEY_api_port_default}}

#######################################################################

usage() {
    cat <<UEND
        usage: $0 (start|stop|validate-all|meta-data|status|monitor)

        $0 manages an OpenStack Orchestration Engine API Service (heat-api) process as an HA resource 

        The 'start' operation starts the heat-api service.
        The 'stop' operation stops the heat-api service.
        The 'validate-all' operation reports whether the parameters are valid
        The 'meta-data' operation reports this RA's meta-data information
        The 'status' operation reports whether the heat-api service is running
        The 'monitor' operation reports whether the heat-api service seems to be working

UEND
}

meta_data() {
    cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="heat-api">
<version>1.0</version>

<longdesc lang="en">
Resource agent for the OpenStack Orchestration Engine API Service (heat-api)
Provides an OpenStack native ReST API that processes API requests  by sending them
to the heat-engine over RPC.
</longdesc>
<shortdesc lang="en">Manages the OpenStack Orchestration Engine API Service (heat-api)</shortdesc>
<parameters>

<parameter name="binary" unique="0" required="1">
<longdesc lang="en">
Location of the OpenStack Orchestration Engine API binary (heat-api)
</longdesc>
<shortdesc lang="en">OpenStack Orchestration Engine API binary (heat-api)</shortdesc>
<content type="string" default="${OCF_RESKEY_binary_default}" />
</parameter>

<parameter name="config" unique="0" required="1">
<longdesc lang="en">
Location of the OpenStack Orchestration Engine API Service (heat-api) configuration file
</longdesc>
<shortdesc lang="en">OpenStack Orchestration Engine API (heat-api) config file</shortdesc>
<content type="string" default="${OCF_RESKEY_config_default}" />
</parameter>

<parameter name="user" unique="0" required="1">
<longdesc lang="en">
User running OpenStack Orchestration Engine API Service (heat-api)
</longdesc>
<shortdesc lang="en">OpenStack Orchestration Engine API Service (heat-api) user</shortdesc>
<content type="string" default="${OCF_RESKEY_user_default}" />
</parameter>

<parameter name="additional_parameters" unique="0" required="0">
<longdesc lang="en">
Additional parameters to pass on to the OpenStack Orchestration Engine API Service (heat-engine)
</longdesc>
<shortdesc lang="en">Additional parameters for heat-api</shortdesc>
<content type="string" />
</parameter>

</parameters>

<actions>
<action name="start" timeout="20" />
<action name="stop" timeout="20" />
<action name="status" timeout="20" />
<action name="monitor" timeout="30" interval="20" />
<action name="validate-all" timeout="5" />
<action name="meta-data" timeout="5" />
</actions>
</resource-agent>
END
}

#######################################################################
# Functions invoked by resource manager actions

heat_api_get_pid(){
  local pid

  pid=$(ps -e | grep heat-api$ | awk -F' ' '{print $1}')
  echo $pid
}

heat_api_check_port() {
# This function has been taken from the squid RA and improved a bit
# The length of the integer must be 4
# Examples of valid port: "1080", "0080"
# Examples of invalid port: "1080bad", "0", "0000", ""

    local int
    local cnt
    
    int="$1"
    cnt=${#int}
    echo $int |egrep -qx '[0-9]+(:[0-9]+)?(,[0-9]+(:[0-9]+)?)*'

    if [ $? -ne 0 ] || [ $cnt -ne 4 ]; then
        ocf_log err "Invalid port number: $1"
        exit $OCF_ERR_CONFIGURED
    fi
}

heat_api_validate() {
    local rc

    check_binary $OCF_RESKEY_binary
    check_binary netstat
    heat_api_check_port $OCF_RESKEY_api_port
    
    # A config file on shared storage that is not available
    # during probes is OK.
    if [ ! -f $OCF_RESKEY_config ]; then
        if ! ocf_is_probe; then
            ocf_log err "Config $OCF_RESKEY_config doesn't exist"
            return $OCF_ERR_INSTALLED
        fi
        ocf_log_warn "Config $OCF_RESKEY_config not available during a probe"
    fi

    getent passwd $OCF_RESKEY_user >/dev/null 2>&1
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "User $OCF_RESKEY_user doesn't exist"
        return $OCF_ERR_INSTALLED
    fi

    true
}

heat_api_status() {
    local pid
    local rc

    pid=$(heat_api_get_pid)
    if [ ! -z $pid ]; then
        ocf_log info "OpenStack Orchestration Engine API (heat-api) is not running"
        return $OCF_NOT_RUNNING
    else 
        return $OCF_SUCCESS
    fi
}

heat_api_monitor() {
    local rc
    local pid

    heat_api_status
    rc=$?

    # If status returned anything but success, return that immediately
    if [ $rc -ne $OCF_SUCCESS ]; then
        return $rc
    fi

    # This is a very basic check if heat-api does its job
    # Check if heat-api listens on the expected port and if it answers a simple api request
    # check if pid fits executable and port fits pid
    pid=$(netstat -tlnp | grep $OCF_RESKEY_api_port  | awk '{split($7,a,"/"); print a[1]}')
    ps -p $pid | grep ' heat-api'
    if [$? -ne 0]; then
      ocf_log err "heat-api is not running on port $OCF_RESKEY_api_port"
      return $OCF_NOT_RUNNING
    fi

    curl -m 59 127.0.0.1:$OCF_RESKEY_api_port &> /dev/null
    if [ $? -ne 0 ]; then
      ocf_log err "heat-api is not answering on port $OCF_RESKEY_api_port"
      return $OCF_NOT_RUNNING
    fi

    # TODO: Create an API request and see if the service answers"

}

heat_api_start() {
    local rc

    # Validate heat-api configuration
    heat_api_validate || exit $?

    # Query heat-api status
    heat_api_status
    rc=$?
    if [ $rc -eq $OCF_SUCCESS ]; then
        ocf_log info "OpenStack Orchestration Engine API (heat-api) already running"
        return $OCF_SUCCESS
    fi

    # run the actual heat-api daemon. Don't use ocf_run as we're sending the tool's output
    # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
    su ${OCF_RESKEY_user} -s /bin/sh -c "/usr/bin/${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
       $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid

    # Spin waiting for the server to come up.
    while true; do
    heat_api_monitor
    rc=$?
    [ $rc -eq $OCF_SUCCESS ] && break
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        ocf_log err "OpenStack Orchestration Engine API (heat-api) start failed"
        exit $OCF_ERR_GENERIC
    fi
    sleep 1
    done

    ocf_log info "OpenStack Orchestration API (heat-api) started"
    return $OCF_SUCCESS
}

heat_api_stop() {
    local rc
    local pid

    heat_api_status
    rc=$?
    if [ $rc -eq $OCF_NOT_RUNNING ]; then
        ocf_log info "OpenStack Orchestration Engine API (heat-api) already stopped"
        return $OCF_SUCCESS
    fi

    # Try SIGTERM
    pid=$(heat_api_get_pid)
    ocf_run kill -s TERM  $pid
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "OpenStack Orchestration Engine API (heat-api) couldn't be stopped"
        exit $OCF_ERR_GENERIC
    fi

    # stop waiting
    shutdown_timeout=15
    if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
    fi
    count=0
    while [ $count -lt $shutdown_timeout ]; do
        heat_api_status
        rc=$?
        if [ $rc -eq $OCF_NOT_RUNNING ]; then
            break
        fi
        count=`expr $count + 1`
        sleep 1
        ocf_log debug "OpenStack Orchestration Engine API (heat-api) still hasn't stopped yet. Waiting ..."
    done

    heat_api_status
    rc=$?
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        # SIGTERM didn't help either, try SIGKILL
        ocf_log info "OpenStack Orchestration Engine API (heat-api) failed to stop after ${shutdown_timeout}s \
          using SIGTERM. Trying SIGKILL ..."
        ocf_run kill -s KILL $pid
    fi

    ocf_log info "OpenStack Orchestration Engine API (heat-api) stopped"

    return $OCF_SUCCESS
}

#######################################################################

case "$1" in
  meta-data)    meta_data
                exit $OCF_SUCCESS;;
  usage|help)   usage
                exit $OCF_SUCCESS;;
esac

# Anything except meta-data and help must pass validation
heat_api_validate || exit $?

# What kind of method was invoked?
case "$1" in
  start)        heat_api_start;;
  stop)         heat_api_stop;;
  status)       heat_api_status;;
  monitor)      heat_api_monitor;;
  validate-all) ;;
  *)            usage
                exit $OCF_ERR_UNIMPLEMENTED;;
esac
